lights:
  - name: Top
    pin_no: 5
  - name: Bottom
    pin_no: 6
#  - name: Not Used
#    pin_no: 13
#  - name: Not Used
#    pin_no: 16
#  - name: Not Used
#    pin_no: 19
#  - name: Not Used
#    pin_no: 20
#  - name: Not Used
#    pin_no: 21
#  - name: Not Used
#    pin_no: 26